# myapp/docker-compose.yml
version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "DB"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
